using IceBloc;
using IceBloc.Frostbite;
using IceBloc.Utility;
using System.Globalization;
using System.Text.RegularExpressions;

namespace IceBlocCLI;

public class Program
{
    public static AssetListItem Selection;

    //dump -assetBank "D:\Tools\Dumps\BF3\bundles\chunks\fc05bd92-bd78-6d3c-3c0f-1c293fe14ef5.chunk"
    //dump -ebx "D:\Tools\Dumps\BF3\bundles\ebx\sound\music\mp_music\mp_music_winning_end_01_wave.ebx"
    static void Main(string[] args)
    {
        CultureInfo.CurrentCulture= CultureInfo.InvariantCulture;
        string command = "";
        while(command != "exit")
        {
            Console.Write("> ");
            command = ParseCommand();
        }
        Environment.Exit(0);
    }

    public static string ParseCommand()
    {
        string[] cmd = Regex.Matches(Console.ReadLine(), @"[\""].+?[\""]|[^ ]+").Cast<Match>().Select(m => m.Value).ToArray();
        for (int i = 0; i < cmd.Length; i++)
        {
                cmd[i] = cmd[i].Replace("\"", "");
        }
        if (cmd.Length > 0)
        {
            switch (cmd[0])
            {
                case "load":
                    if (cmd[1] == "-game")
                    {
                        Settings.GamePath = cmd[2];
                        IO.LoadGame();
                    }
                    else if (cmd[1] == "-file")
                        IO.LoadSbFile(cmd[2]);
                    break;
                case "dump":
                    if (cmd[1] == "-assetBank")
                        DumpAssetBank(cmd[2]);
                    if (cmd[1] == "-ebx")
                        DumpEbx(cmd[2]); break;
                case "select":
                    if (cmd.Length == 1)
                        Console.WriteLine("Current selection is: " + Selection.Name);
                    SelectAsset(cmd[1]); break;
                case "extract":
                    Selection.Export(); break;
                case "setgame":
                    if (!Enum.TryParse(cmd[1], out Settings.CurrentGame))
                        Console.WriteLine("Unrecognized game."); break;
                case "getgame":
                    Console.WriteLine("Current Game: " + Settings.CurrentGame); break;
                default: break;
            }
            return cmd[0];
        }
        return "";
    }

    public static void SelectAsset(string asset)
    {
        Selection = IO.Assets[asset];
    }

    public static void DumpEbx(string path)
    {
        var dbx = new Dbx(path);
        dbx.Dump(@"D:\test.ebx");
    }

    public static void DumpAssetBank(string path)
    {
        GenericData gd = new GenericData(File.OpenRead(path));

        if (!Path.Exists($"Output\\{Settings.CurrentGame}"))
            Directory.CreateDirectory($"Output\\{Settings.CurrentGame}");

        string exportPath = $"Output\\{Settings.CurrentGame}\\" + Path.GetFileNameWithoutExtension(path) + "_dump.txt";
        using var w = new StreamWriter(exportPath, false);
        
        w.WriteLine($"Generated by IceBlocCLI\n");
        w.WriteLine($"Classes:\n");
        foreach (var cl in gd.Classes)
        {
            if (cl.Value.Elements.Count > 0)
            {
                w.WriteLine($"{cl.Value.Name}:");
                foreach (var field in cl.Value.Elements)
                {
                    w.WriteLine($"    {field.Type} {field.Name}");
                }
                w.WriteLine($"");
            }
        }
        w.WriteLine("Data:\n");
        foreach (var v in gd.Data)
        {
            using var s = new MemoryStream(v.Key.ToArray());
            using var r = new BinaryReader(s);
            r.ReadGdDataHeader(v.Value, out uint hash, out uint type, out uint baseOffset);
            var data = gd.ReadValues(r, baseOffset, type, v.Value);

            w.WriteLine($"{gd.Classes[type].Name} \"{data["__name"]}\", {(v.Value ? "BE" : "LE")}:");
            foreach (var d in data)
            {
                w.Write($"    {d.Value.GetType().Name} {d.Key}");
                if (d.Value is Array)
                {
                    w.Write($"[{(d.Value as Array).Length}] = ");
                    foreach (object val in (d.Value as Array))
                    {
                        w.Write($"{val}, ");
                    }
                    w.WriteLine("");
                }
                else
                {
                    w.WriteLine(" = " + d.Value.ToString());
                }
            }
            w.WriteLine("");
        }

        Console.WriteLine("Saved to " + exportPath);
    }
}